server:
  port: 8082
ys:
  item:
    url: http://127.0.0.1:8081/item/
    serviceId: ys-microservice-item

spring:
  application:
    name: ys-microservice-order #指定服务名

eureka:
  client:
    registerWithEureka: false #是否将自己注册到Eureka服务中，默认为true
    fetchRegistry: true #是否从Eureka中获取注册信息，默认为true
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://ys:ys123@127.0.0.1:6868/eureka/